#!/bin/bash

# 🛡️ Script: clamav-all
# Descrição: Verificação e atualização completa com o ClamAV
# Versão: 1.0.0

if [[ "${1:-}" == "--help" ]]; then
  echo "🛡️  Script clamav-all"
  echo "Uso: clamav-all [--help]"
  echo
  echo "Este script executa uma varredura completa e atualiza as definições do ClamAV."
  echo
  echo "Opções:"
  echo "  --help         Exibe esta mensagem de ajuda"
  exit 0
fi

freshclam
clamscan -r / --quiet --log=/var/log/hardening/clamav.log
