name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck yamllint
    
    - name: Lint shell scripts
      run: |
        find scripts/ -name "*.sh" -exec shellcheck {} \;
    
    - name: Validate YAML files
      run: |
        find . -name "*.yaml" -o -name "*.yml" | xargs yamllint
    
    - name: Run tests
      run: |
        chmod +x tests/test_runner.sh
        ./tests/test_runner.sh
    
    - name: Test installation
      run: |
        sudo make install
        # Testar se scripts foram instalados corretamente